### ISSUE TITLE
Example in notebook throws INVALID_ARGUMENT error 

### ISSUE THREAD

**Issue by knitlybak** [Stability-AI/stability-sdk#101]
Hello,

The code snippet that I was using was working up to 2 weeks ago that I checked and it is almost identical with the example notebook.
```
import os
import io
import warnings

from PIL import Image
from stability_sdk import client
import stability_sdk.interfaces.gooseai.generation.generation_pb2 as generation
from dotenv import load_dotenv

load_dotenv()


def main():
    stability_api = client.StabilityInference(
        key=os.environ["STABILITY_KEY"],
        verbose=True,
    )
    answers = stability_api.generate(
        prompt="houston, we are a 'go' for launch!",
        seed=34567,  # if provided, specifying a random seed makes results deterministic
        steps=30,  # defaults to 50 if not specified
    )
    for resp in answers:
        for artifact in resp.artifacts:
            if artifact.finish_reason == generation.FILTER:
                return warnings.warn(
                    "Your request activated the API's safety filters and \
              could not be processed."
                    "Please modify the prompt and try again."
                )
            if artifact.type == generation.ARTIFACT_IMAGE:
                image_name = "rocket"
                path = os.environ("IMAGE_DIR") + image_name + ".png"
                img = Image.open(io.BytesIO(artifact.binary))
                img.save(path)
                print("done")


if __name__ == "__main__":
    main()
```
I believed that the only parameter that you need to input is the prompt. It throws the error:

Traceback (most recent call last):
  File "/Users/blackbak/Github/Suede/Exploratory/stabilityapi.py", line 42, in <module>
    main()
  File "/Users/blackbak/Github/Suede/Exploratory/stabilityapi.py", line 23, in main
    for resp in answers:
  File "/opt/anaconda3/envs/suede/lib/python3.9/site-packages/stability_sdk/client.py", line 300, in generate
    for answer in self.stub.Generate(rq, **self.grpc_args):
  File "/opt/anaconda3/envs/suede/lib/python3.9/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/opt/anaconda3/envs/suede/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Must provide image parameters."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:104.18.21.212:443 {created_time:"2022-10-21T13:21:01.529499-04:00", grpc_status:3, grpc_message:"Must provide image parameters."}"

**Comment by knitlybak** [comment]
I downgraded Python to 3.8 and it works. Are newer python versions not supported?

**Comment by Vivihung** [comment]
I hit the same error from python pkg (stability_sdk) started this week (Nov 7th). It seems a breaking change in the package/API. :(
Downgrade Python doesn't seem a good long term solution.

**Comment by Garinmckayl** [comment]
facing similar issues recently

**Comment by photomz** [comment]
@knitlybak I faced this issue and fixed it. You're triggering the inappropriate content filter. You must handle gRPC errors separately, or make the SD prompt so tame to not trigger the filter:

```py
import grpc

try:
    for resp in answers:
        for artifact in resp.artifacts:
            if artifact.finish_reason == generation.FILTER:
                return warnings.warn(
                    "Your request activated the API's safety filters and \
            could not be processed."
                    "Please modify the prompt and try again."
                )
            if artifact.type == generation.ARTIFACT_IMAGE:
                image_name = "rocket"
                path = os.environ("IMAGE_DIR") + image_name + ".png"
                img = Image.open(io.BytesIO(artifact.binary))
                img.save(path)
                print("done")

except grpc.RpcError as e:
    if e.code() == grpc.StatusCode.INVALID_ARGUMENT:
        # Handle your error
    else:
        raise e
```

Stability SDK follows a standard `grpc` schema and [status codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md), so you can catch their errors with the `grpc` Python package.

Hope this helps!
