### ISSUE TITLE
Error generating image on Windows and Linux

### ISSUE THREAD

**Issue by geosemaan** [Stability-AI/stability-sdk#13]
I'm just testing out the SDK and I'm getting a different error on Windows and Linux.

I got `OSError: [Errno 22] Invalid argument` on Windows so I figured it must be Windows directories, so I installed Linuxmint and gave it a shot only to get this error `TypeError: __call__() got an unexpected keyword argument 'wait_for_ready'` 

Windows
````
PS C:\Users\User\Desktop\Stability\stability-sdk-main\src\stability_sdk> python client.py -W 512 -H 512 "A stunning house."
2022-08-26 15:50:59,819 INFO client.py(7812) - Opening channel to grpc.stability.ai:443
2022-08-26 15:50:59,823 INFO client.py(7812) - Channel opened to grpc.stability.ai:443
2022-08-26 15:50:59,824 INFO client.py(7812) - Sending request.
2022-08-26 15:51:05,177 INFO client.py(7812) - Got keepalive 8e0e8b37-ab2f-48b7-bbd3-7cf8ee7cb3ef in 5.35s
2022-08-26 15:51:05,877 INFO client.py(7812) - Got d5b78459-bbc5-4560-a467-61eb47bbd73d with ['ARTIFACT_IMAGE', 'ARTIFACT_CLASSIFICATIONS'] in 0.70s
Traceback (most recent call last):
  File "client.py", line 374, in <module>
    for artifact in artifacts:
  File "client.py", line 92, in process_artifacts_from_answers
    with open(out_p, "wb") as f:
OSError: [Errno 22] Invalid argument: 'generation-ee77115a-ce17-48de-ac67-9ace16ba0d0f:0:0-d5b78459-bbc5-4560-a467-61eb47bbd73d-0.png'
````
Linuxmint
````
~/Desktop/stability-sdk-main/src/stability_sdk$ python3 client.py -W 512 -H 512 "A stunning house."
2022-08-26 15:58:11,459 INFO client.py(1827) - Opening channel to grpc.stability.ai:443
2022-08-26 15:58:11,461 INFO client.py(1827) - Channel opened to grpc.stability.ai:443
2022-08-26 15:58:11,461 INFO client.py(1827) - Sending request.
Traceback (most recent call last):
  File "client.py", line 374, in <module>
    for artifact in artifacts:
  File "client.py", line 75, in process_artifacts_from_answers
    for resp in answers:
  File "client.py", line 246, in generate
    for answer in self.stub.Generate(rq, **self.grpc_args):
TypeError: __call__() got an unexpected keyword argument 'wait_for_ready'
````

**Comment by geosemaan** [comment]
> @geosemaan Seems i might be right.
> 
> There is a pull request exactly for this error:
> 
> #9

This fixed the error on Windows but not on Linuxmint, I'm still getting the same error `TypeError: __call__() got an unexpected keyword argument 'wait_for_ready'`
