### ISSUE TITLE
Error in `pip install stability-sdk` on M1 mac

### ISSUE THREAD

**Issue by mdarshad1000** [Stability-AI/stability-sdk#154]
Collecting grpcio==1.48.1
  Using cached grpcio-1.48.1.tar.gz (22.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/dx/_xl5lmnd4j98mnf0msqlfpr80000gn/T/pip-install-4l32z9bc/grpcio_55f75c75188e48a98ebb7a8f0ca6af60/setup.py", line 263, in <module>
          if check_linker_need_libatomic():
        File "/private/var/folders/dx/_xl5lmnd4j98mnf0msqlfpr80000gn/T/pip-install-4l32z9bc/grpcio_55f75c75188e48a98ebb7a8f0ca6af60/setup.py", line 219, in check_linker_need_libatomic
          cpp_test = subprocess.Popen(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1717, in _execute_child
          and os.path.dirname(executable)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 152, in dirname
          p = os.fspath(p)
      TypeError: expected str, bytes or os.PathLike object, not list
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

This is the error I am receiving.

**Comment by alibeyram** [comment]
use python=3.8 

this worked for me.
```
conda create -n stability python=3.8
conda activate stability
pip install stability-sdk
```

**Comment by mdarshad1000** [comment]
Great thanks! It worked.

**Comment by ChristopherValore** [comment]
Closing issue due to problem resolved by using one of our supported versions of Python.
