### ISSUE TITLE
client.py usage disagrees with generation.proto from latest version from api-interfaces

### ISSUE THREAD

**Issue by hafriedlander** [Stability-AI/stability-sdk#38]
generation.proto from api-interfaces has ImageParameters and ClassifierParameters in a oneof (https://github.com/Stability-AI/api-interfaces/blob/main/src/proto/generation.proto#L177)

However client.py sets ClassifierParameters by default, meaning the ImageParameters get ignored (https://github.com/Stability-AI/stability-sdk/blob/main/src/stability_sdk/client.py#L237)

(Since there isn't anyone raising a bug about ImageParameters not working, does the current live server not use the latest version of api-interfaces?)

**Comment by sayanarijit** [comment]
Now I'm getting this error:

```
(.venv) ➜  stability-sdk git:(main) ✗ python3 -m stability_sdk.client -W 512 -H 512 "A stunning house."
2022-09-20 10:14:03,306 INFO client.py(79734) - Opening channel to grpc.stability.ai:443
2022-09-20 10:14:03,310 INFO client.py(79734) - Channel opened to grpc.stability.ai:443
2022-09-20 10:14:03,310 INFO client.py(79734) - Sending request.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/src/stability_sdk/client.py", line 469, in <module>
    for artifact in artifacts:
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/src/stability_sdk/client.py", line 99, in process_artifacts_from_answers
    for resp in answers:
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/src/stability_sdk/client.py", line 308, in generate
    for answer in self.stub.Generate(rq, **self.grpc_args):
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Must provide image parameters."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:104.18.21.212:443 {created_time:"2022-09-20T10:14:04.245607616+05:30", grpc_status:3, grpc_message:"Must provide image parameters."}"'
```

Not sure if it's related.

**Comment by sayanarijit** [comment]
Not sure if it's related, so created a [separate issue](https://github.com/Stability-AI/stability-sdk/issues/54).

**Comment by chigozienri** [comment]
Thanks for reporting @hafriedlander

`api-interfaces` is the canonical version, and should always be in sync with the production server

We no longer set ClassifierParameters in the python sdk, thanks to @sayanarijit!

Closing
