### ISSUE TITLE
UNKNOWN:Illegal header value 

### ISSUE THREAD

**Issue by alinabel** [Stability-AI/stability-sdk#40]
`E0913 23:00:44.799000000  8924 src/core/lib/security/credentials/plugin/plugin_credentials.cc:86] validate_metadata_from_plugin: UNKNOWN:Illegal header value {raw_bytes:"42 65 61 72 65 72 20 16 \'Bearer .\'\x00", offset:7, created_time:"2022-09-13T20:00:44.7994232+00:00"}
E0913 23:00:44.804000000  8924 src/core/lib/security/credentials/plugin/plugin_credentials.cc:87] Plugin added invalid metadata value.
Traceback (most recent call last):
  File "C:\Users\onyx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\onyx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\onyx\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\onyx\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\onyx\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\onyx\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path     
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\onyx\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\onyx\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code    
    exec(code, run_globals)
  File "c:\Users\onyx\a\ali\runScript.py", line 35, in <module>
    for resp in answers:
  File "c:\Users\onyx\a\ali\lib\site-packages\stability_sdk\client.py", line 300, in generate
    for answer in self.stub.Generate(rq, **self.grpc_args):
  File "c:\Users\onyx\a\ali\lib\site-packages\grpc\_channel.py", line 426, in __next__
    return self._next()
  File "c:\Users\onyx\a\ali\lib\site-packages\grpc\_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Illegal metadata"
        debug_error_string = "UNKNOWN:Error received from peer grpc.stability.ai:443 {grpc_message:"Illegal metadata", grpc_status:14, created_time:"2022-09-13T20:00:44.8064471+00:00"}"
>
`

I receive this error ? how to fix ?

**Comment by alinabel** [comment]
the reason of this because not providing an API key so make sure you're past the apikey from right click and save not CTRL-V
