### ISSUE TITLE
error: Must provide image parameters

### ISSUE THREAD

**Issue by sayanarijit** [Stability-AI/stability-sdk#54]
Started getting this error after [this commit was merged](https://github.com/Stability-AI/stability-sdk/commit/10c68658790f584b856756e54136204297c9f870).

```
(.venv) ➜  stability-sdk git:(main) ✗ python3 -m stability_sdk.client -W 512 -H 512 "A stunning house."
2022-09-20 12:38:58,908 INFO client.py(100811) - Opening channel to grpc.stability.ai:443
2022-09-20 12:38:58,911 INFO client.py(100811) - Channel opened to grpc.stability.ai:443
2022-09-20 12:38:58,911 INFO client.py(100811) - Sending request.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/src/stability_sdk/client.py", line 469, in <module>
    for artifact in artifacts:
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/src/stability_sdk/client.py", line 99, in process_artifacts_from_answers
    for resp in answers:
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/src/stability_sdk/client.py", line 308, in generate
    for answer in self.stub.Generate(rq, **self.grpc_args):
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/sayanarijit/Documents/GitHub/stability-sdk/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Must provide image parameters."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:---------- {grpc_message:"Must provide image parameters.", grpc_status:3, created_time:"2022-09-20T12:38:59.84627592+05:30"}"
>

```

Found the cause to be this change: https://github.com/Stability-AI/stability-sdk/commit/10c68658790f584b856756e54136204297c9f870#diff-63cf1f93510f4408aad0aea8b6b26f505c4edfcc8735c273f17966cb7a8380dbL170-L174

**Comment by dholbrook86** [comment]
Also having this issue.

```
2022-09-22 16:37:03,307 INFO client.py(6617) - Opening channel to grpc.stability.ai:443
2022-09-22 16:37:03,312 INFO client.py(6617) - Channel opened to grpc.stability.ai:443
2022-09-22 16:37:03,313 INFO client.py(6617) - Sending request.

grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Must provide image parameters."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:104.18.21.212:443 {created_time:"2022-09-22T16:37:03.518253-06:00", grpc_status:3, grpc_message:"Must provide image parameters."}"
```

**Comment by kamangir** [comment]
solution: https://github.com/Stability-AI/stability-sdk/pull/55
