### ISSUE TITLE
Not getting PNG output from command line client, but long-name empty files instead

### ISSUE THREAD

**Issue by Markdood88** [Stability-AI/stability-sdk#57]
The client.py isnt outputting PNGs in the directory like the instructions say. Note, i'm running on an Anaconda env.

![image](https://user-images.githubusercontent.com/1495254/191815221-d1abf0c2-40aa-4c27-b027-773a67df6a16.png)

I run the above, and it outputs the below

![image](https://user-images.githubusercontent.com/1495254/191815425-72704846-c942-470c-8cb3-492ce0ce1987.png)

super long file name, not long enough to include the .json bit at the end, looks like its an empty file, generally not sure what to do with this, the instructions are unclear. Please advise.

**Comment by TigerForge2** [comment]
Same problem.

**Comment by kamangir** [comment]
Same problem here.

```bash
python3 -m stability_sdk.client -W 512 -H 512 "A stunning house."
```
```
2022-09-25 16:22:51,737 INFO client.py(75806) - Opening channel to grpc.stability.ai:443
2022-09-25 16:22:51,740 INFO client.py(75806) - Channel opened to grpc.stability.ai:443
2022-09-25 16:22:51,740 INFO client.py(75806) - Sending request.
Traceback (most recent call last):
  File "/Users/kamangir/opt/miniconda3/envs/abcli/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kamangir/opt/miniconda3/envs/abcli/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kamangir/git/blue-stability/src/stability_sdk/client.py", line 469, in <module>
    for artifact in artifacts:
  File "/Users/kamangir/git/blue-stability/src/stability_sdk/client.py", line 99, in process_artifacts_from_answers
    for resp in answers:
  File "/Users/kamangir/git/blue-stability/src/stability_sdk/client.py", line 308, in generate
    for answer in self.stub.Generate(rq, **self.grpc_args):
  File "/Users/kamangir/opt/miniconda3/envs/abcli/lib/python3.9/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/Users/kamangir/opt/miniconda3/envs/abcli/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Must provide image parameters."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:104.18.21.212:443 {created_time:"2022-09-25T16:22:56.875848-07:00", grpc_status:3, grpc_message:"Must provide image parameters."}"
```

**Comment by chigozienri** [comment]
@Markdood88 Thanks for the report. There should be two files generated, the .json and the .png.
I can't replicate it locally, but I am keen to get it fixed.
What O/S are you using? It's possible that it's to do with the filename length, as in #9

@kamangir I think this is a different issue - yours might be solved by updating the pip package

**Comment by silvertooth08** [comment]
![stableaierror](https://user-images.githubusercontent.com/78120174/192831736-9ddd21a8-4586-4020-8bec-c875f9b914b0.jpg)

I also have the same error my O/S is Windows 11. I allowed for longer file names but still get this sort of outcome
![stableaioutput](https://user-images.githubusercontent.com/78120174/192831756-17b9154e-8934-46a8-888b-6efec1581ba1.jpg)

**Comment by Hugobox** [comment]
I also had the same problem on Windows. My quickfix was changing line 101 of client.py to: 
#artifact_p = f"{prefix}-{resp.answer_id}"

**Comment by Hugobox** [comment]
Ok found out that the client.py you get from pip install is not the latest, as this bug has been fixed in this merge:
https://github.com/Stability-AI/stability-sdk/pull/67
